### ISSUE TITLE
How to force a fix width?

### ISSUE THREAD

**Issue by danicarla** [PhilippeMarcMeyer/vanillaSelectBox#13]
Hi guys... how to force a fix width in input type multiple?

I try using **size** atribut but the size of the field still moves

**Comment by PhilippeMarcMeyer** [comment]
Hello Danicarla,
Il use the size attribute of the select to list selected items in the top button

if you choose 3 and check 3 car for instance "Abarth,Alfa Romeo,Alpine" you'll see this list in the top button
but if you clic a fourth item you pass the limit and the top button now holds "4 items"

there is no option for a fixed width
but you can play with the maxWidth option : choose a short maxWidth

If you can get a nice result then I will add a minWidth option and you will just choose the same amount for both
let me know
