### ISSUE TITLE
setValue('all') does not properly set "select all" item.

### ISSUE THREAD

**Issue by RWebster-Noble** [PhilippeMarcMeyer/vanillaSelectBox#15]
When `setValue('all')` is called all items are successfully selected but the "select all" item remains. 
![image](https://user-images.githubusercontent.com/27361135/98350230-f82b0080-2012-11eb-871a-980336c7641c.png)
When the user clicks this it does not do anything but change the text to "clear all". 

Instead when `setValue('all')` is called it should behave the same as the user clicking the "select all" item and the "select all" item should change to "clear all".

This can be easily replicated by running `selectBox2.setValue('all');` on the demo page.

**Comment by RWebster-Noble** [comment]
As an continuation to this: A potential improvement may be when all items are selected then the "Select All" item could automatically become checked and turn into "Clear All".

This would remove my need to call `setValue('all')` as all the items are set as selected server-side.

**Comment by PhilippeMarcMeyer** [comment]
Thank you for this excellent issue. the setValue('all') command was not consistent with the checkbox "select all"
I also managed to link the search result with the select all / clear all behaviour => anly the found items are checked / unchecked
Hope it meets your needs
note that if le select dom element has all its options selected prior to its tranformation into a vanilla selectbox, all the items will be checked at start

**Comment by RWebster-Noble** [comment]
That is great! Thank you for updating the code.

Unfortunately I am not seeing what you described. Specifically:

> note that if le select dom element has all its options selected prior to its tranformation into a vanilla selectbox, all the items will be checked at start

Am I doing something wrong?

Here is an example of what I'm seeing

![image](https://user-images.githubusercontent.com/27361135/98574398-c71b2c00-22af-11eb-9579-8932860f3dae.png)

```html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="./vanillaSelectBox.css" />
    <script src="./vanillaSelectBox.js"></script>
</head>

<select id="brandsMulti" multiple="">
    <option selected="true" value="Abarth">Abarth</option>
    <option selected="true" value="Alfa Romeo">Alfa Romeo</option>
    <option selected="true" value="Alpine">Alpine</option>
    <option selected="true" value="Aston Martin">Aston Martin</option>
    <option selected="true" value="Audi">Audi</option>
</select>

<script type="text/javascript">
    var mySelect = new vanillaSelectBox("#brandsMulti", {
    });
    mySelect.enable();
</script>

</html>
```

Also it would be great if the user selected all items then the "Select All" item would automatically become selected.

**Comment by PhilippeMarcMeyer** [comment]
All items are not selected are they ? Just a few

**Comment by PhilippeMarcMeyer** [comment]
OK i've got it ! Corrected : i forgot to check the select all checkbox at init time all items are selected.
I had done it on setValue('all') onvly

the main upgrade is that you can click "select all/clear all" while seraching and select/clear only the found items.

**Comment by PhilippeMarcMeyer** [comment]
BTW Rwebster noble, you may use a size attribute in your select tag to limit the number of items shown in the header button :

<select id="brands" multiple size="3">

![image](https://user-images.githubusercontent.com/2178299/98637042-39c7ee00-2328-11eb-8cbd-64590c7e4703.png)

**Comment by PhilippeMarcMeyer** [comment]
Don't hesitate to mail me if you need advices on this issue or on web developpement :-)
