### ISSUE TITLE
copy attributes from original select

### ISSUE THREAD

**Issue by HH-kkuijk** [PhilippeMarcMeyer/vanillaSelectBox#19]
Would it be possible to copy all attributes from the original select options to the new one, for example. If I have added data-color="#ff0000" to an option in the original select, I would like to see that value copied to the cloned select option. It would be nice if not only data-attr would be copied but any kind of attribute in the option html.

**Comment by PhilippeMarcMeyer** [comment]
Done ! it's v 0.55
Thanks for that ecellent idea !!!

**Comment by HH-kkuijk** [comment]
GREAT!!! It might be a good option to put the text inside the LI into a span, giving it more options for adding custom styling

**Comment by PhilippeMarcMeyer** [comment]
Experiment my friend ! :-)
I'd be happy to hear about you whenever you want

Cheers

Philippe

**Comment by HH-kkuijk** [comment]
Hi Phillippe, I mean that it would be great to have the cloned dropdown filled with a span.

This is the code that is generated now:
`<li data-value="all" data-text="Select All" value="all" class="active" data-selected="true">Clear All</li>`

I would suggest putting the text in a span, the generated html would be like:
`<li data-value="all" data-text="Select All" value="all" class="active" data-selected="true"><span>Clear All</span></li>`

This way there are more option for styling because you can use the li:before and li:after but also li > span:before and li > span:after
