### ISSUE TITLE
InvalidCharacterError

### ISSUE THREAD

**Issue by gitFrank** [PhilippeMarcMeyer/vanillaSelectBox#2]
If options have more as one class:
InvalidCharacterError: String contains an invalid character

In my case works not:
`<option value="219" class="flag-padding flag-box"...`
works:
`<option value="219" class="flag-box"...`

**Comment by PhilippeMarcMeyer** [comment]
Thank you so much ! 
I will correct it soon

**Comment by PhilippeMarcMeyer** [comment]
Corrected
Thank bug hunter !
