### ISSUE TITLE
Move styling

### ISSUE THREAD

**Issue by HH-kkuijk** [PhilippeMarcMeyer/vanillaSelectBox#20]
I really like this plugin! As imporvement I would suggest moving all inline styling to the css sheet and adding/removing classes. 

For example: 
- the button styling, set it in the stylsheet instead of inline (instead of the inline style use it in the style sheet, if needed with !important)
- add a class to indicate the dropdown is visible or hidden (.vsb-menu .show for example)
- add span for the text in the li for more styling options

**Comment by PhilippeMarcMeyer** [comment]
Well I agreed for importing the options attributes in the plugin
but I'm absolutly not convinced by more styling : i put the styling on the button recently and on purpose : to protect its geometry and appareance from css interactions with the host page.
