### ISSUE TITLE
exception if no attributes

### ISSUE THREAD

**Issue by Ian1971** [PhilippeMarcMeyer/vanillaSelectBox#21]
I  noticed that if the attributes collection is empty it ends up with originalAttrs undefined here.

https://github.com/PhilippeMarcMeyer/vanillaSelectBox/blob/c373abcfbfa111798dd4be0a8ba1c8904b8d29cb/vanillaSelectBox.js#L284

**Comment by PhilippeMarcMeyer** [comment]
Thank you Ian

Its fixed
