### ISSUE TITLE
[QUESTION] How to get the actual values represented in an array?

### ISSUE THREAD

**Issue by WeebHiroyuki** [PhilippeMarcMeyer/vanillaSelectBox#23]
Hey. I'm doing some client-side rendering and request handling so the form isn't submitted directly with HTML. It uses some external JavaScript (fetch) to fulfil requests. For some reason, I can't get an array of the selected options when using
```js
const formData = new FormData(document.querySelector(`${formID}`));
```
and `formData.entries()`. It returns a string even if I selected multiple options.

Is there any way to get the actual values of the array (if multiple options are selected)?

**Comment by PhilippeMarcMeyer** [comment]
On submit process you could gather the ids in a delimited list and put it into an hidden field

use getValues() little function I use in index.html 
do a join(',') and put it into the hidden field.

I could update VSB to provide a a hidden field

**Comment by PhilippeMarcMeyer** [comment]
I have just released version v0.57 : Added an input of type hidden with a name attribute equal to the select id which holds the selected options delimited by commas

don't give a name to your original select element and you'll get the result ex : '5,6,9,13' in an input hidden

```
<select id='myselect'>
....
</select>

<input type='hidden' name='myselect' value='5,6,9,13''/>
```

Hope it helps

**Comment by WeebHiroyuki** [comment]
> 
> 
> On submit process you could gather the ids in a delimited list and put it into an hidden field
> 
> use getValues() little function I use in index.html
> do a join(',') and put it into the hidden field.
> 
> I could update VSB to provide a a hidden field

Hi there. I fixed the issue. It wasn't directly an issue with your code, but it'd be appreciated if you could add direct support for client-side requests (with axios, node-fetch, etc.)
I added in jQuery and somehow extracted the value. Thanks though.

**Comment by PhilippeMarcMeyer** [comment]
You don't need need jquery : with the new version I made for you, just do document.querySelector("input[name='brandsMulti']").value where your select id is #brandsMulti
You can directly get the values by submiting the form : brandsMulti='comma delimited list...'

I certainly don't like you have to use jQuery with vanillaSelectBox!
If you want to show me your code, maybe I can help (in discussion or by mail)

**Comment by PhilippeMarcMeyer** [comment]
I have downgraded to v 0.56 : no hidden input holding the selected options values as it is two slow and heavy with large drop downs.
sorry for the inconvenience ! 
:-(
