### ISSUE TITLE
"minWidth" option is not honored if "maxWidth" is not explicitly set

### ISSUE THREAD

**Issue by Secras** [PhilippeMarcMeyer/vanillaSelectBox#28]
If the "minWidth" option is explicitly set, but "maxWidth" option not, "minWidth" option will not be honored. 
In vanillaSelectBox.js line 84 and following (master), "maxWidth" is checked twice if it is set. The second one should probably be a check if "minWidth" is set. 

Best regards

**Comment by PhilippeMarcMeyer** [comment]
Thank You Secras ! to help scatterbrain-me :-)
