### ISSUE TITLE
Problems inside of a table?

### ISSUE THREAD

**Issue by gitFrank** [PhilippeMarcMeyer/vanillaSelectBox#3]
Hi, thanks for the really nice plugin.
Seems inside of table it works not like expected. 

In my test case the div.vsb-menu will displayed on top left corner of the browser.
In your demo page (i created a table around div#demo-single with dev-tools) your button doesn't react anymore.

Yes, i can try to work without tables. :-)

**Comment by PhilippeMarcMeyer** [comment]
Could you send me your code ?
So I can figure out what's happening
You can use my email

**Comment by PhilippeMarcMeyer** [comment]
I'm glad you could make it work !
I've tested this
`<div class="demo-zone" >
	<label>Testting a bug in tables : </label>
	<table>
	<tr><td>
	<select id="testInTable" multiple size="3" style="display: none;">
		<option value=""></option>
		<option value="Abarth">Abarth</option>
		<option value="Alfa Romeo">Alfa Romeo</option>
		<option value="Alpine">Alpine</option>
		<option value="Aston Martin">Aston Martin</option>
		<option value="Audi">Audi</option>
		<option value="Bentley">Bentley</option>
		<option value="BMW">BMW</option>
		<option value="Tesla">Tesla</option>
		<option value="Toyota">Toyota</option>
		<option value="Volkswagen">Volkswagen</option>
		<option value="Volvo">Volvo</option>
	</select>
	</td></tr>
	</table>
</div>`

and got no bug
Your inclusion in a table must be complex with a css interaction somewhere

Thanks anyway for the report
enjoy you plugin and if you have any idea of improvement let me know
