### ISSUE TITLE
Change event is dispatched on the page load

### ISSUE THREAD

**Issue by jake-melikov** [PhilippeMarcMeyer/vanillaSelectBox#30]
When the select box is initially generated, the `privateSendChange` function is [called](https://github.com/PhilippeMarcMeyer/vanillaSelectBox/blob/8f844d3571f7fd13fd6ac93a6f87c0b08ba1effb/vanillaSelectBox.js#L554). Is this intentional? Shouldn't the change event be emitted only for changes coming from a user? 

The [culprit line](https://github.com/PhilippeMarcMeyer/vanillaSelectBox/blob/8f844d3571f7fd13fd6ac93a6f87c0b08ba1effb/vanillaSelectBox.js#L554) was added in this [commit](https://github.com/PhilippeMarcMeyer/vanillaSelectBox/commit/99fe32f541a3d7ec3aeb98164cf8e0a07ce94dd4). That commit was later (partially) [reverted](https://github.com/PhilippeMarcMeyer/vanillaSelectBox/commit/6679a9d31653d83557d44955b9fa20916baa18d0), but the culprit line stayed there. This makes me more suspicious about it.

In my application, I'm listening for user change events and it causes small inconvenience when this event is triggered on the page load.

**Comment by PhilippeMarcMeyer** [comment]
You are perfectly right and its a pleasure to have a good issue like this ! thanks. privateSendChange has been removed on init
