### ISSUE TITLE
Feature Request: Is it possible to have like two or more levels of multi select?

### ISSUE THREAD

**Issue by swaroopg92** [PhilippeMarcMeyer/vanillaSelectBox#35]
Basically something like this

- [ ] A
- [ ] B
  - [ ] b1
  - [ ] b2
- [ ] C

Not sure if its already possible, if yes, then can you please let me know how to do it?
Thanks.
By the way, thank you for this amazing package.

**Comment by PhilippeMarcMeyer** [comment]
Not with the current version. But that's one of my projects. There is a  plugin called fancyTree that allows multi-levels.

**Comment by swaroopg92** [comment]
I see. Thanks for this project btw.
I will checkout fancyTree and also patiently wait for this to be implemented here.

**Comment by PhilippeMarcMeyer** [comment]
I dont have much time : what I plan in the future is to use selects with optgroups has a base for 2 levels selects it means we would have max 2 levels

**Comment by swaroopg92** [comment]
I completely understand. 2 levels should suffice for my application. Thanks again.
