### ISSUE TITLE
this.root is nul

### ISSUE THREAD

**Issue by gitFrank** [PhilippeMarcMeyer/vanillaSelectBox#4]
Hi, if i use the script global (in my case in the backend of a CMS) and i don't have a page with attribute "multiple", this JS error occours:
TypeError: this.root is null

It's not important, but can I avoid it?

**Comment by PhilippeMarcMeyer** [comment]
Hello Frank,
Well, it not very clear to me : the first parameter of the function is a dom selector, for instance "#myselect", so you have to provide an existing dom selector for vsb to work. Even if the prepare things under the hood in the back, the init of vsb should begin after the page is fully loaded, un less it won't work. Cheers
