### ISSUE TITLE
Autocomplete with limited size for huge data

### ISSUE THREAD

**Issue by brunoneumann** [PhilippeMarcMeyer/vanillaSelectBox#49]
Hello, thanks for this nice plugin!

Can I use this plugin for a search with huge data from server? 
In this case I'd type in autocomplete input and content would be loaded on demand (showing max 10 items for example). 

I checked the ajax demo example, but it gets all data. Trying to figure it out to redraw box with new content without create a new vanillaSelectBox() instance.

**Comment by PhilippeMarcMeyer** [comment]
It would require some debouncing + ajax call with a tree redraw independant of the original SELECT TAG
(?) The already checked items would be preserved even if there are not a the search, allowing several search and check sessions
That very interesting... To study so.... By curiosity : what is you back language ?
