### ISSUE TITLE
Adding options to multi without using built in remote function

### ISSUE THREAD

**Issue by JacobWoolbright** [PhilippeMarcMeyer/vanillaSelectBox#55]
In my website I currently have a system to grab a list of items and put them into a selector, which works perfectly, however when converting the select element into the vanilla select box all the items disappear. What's the best way to go about adding items without using the built in JSON system?

code:

```html
<select name="neat" id="neat" multiple></select>

<script>

          $.get("http://LINK", function( data ) {

              var splitBUs = data.split("\n")
              var list = document.getElementById('neat');

              splitBUs.forEach(function(item){
                  var option = document.createElement('option');
                  option.value = item;
                  option.innerHTML = item;
                  list.appendChild(option);
              });
          });

          let selectBox = new vanillaSelectBox("#neat",{"maxHeight":200,search:true, "placeHolder": "Subtype"});
          selectBox.setValue('all')
</script>
```

**Comment by PhilippeMarcMeyer** [comment]
Put the vanillaSelectBox call inside your get procedure 
your function(data) is a callback ie a function called when your $.get() ajax call terminates
the ajax call is asynchronous so in your code the vanillaSelectBox() call is done before the data si available
