### ISSUE TITLE
Multiples selects

### ISSUE THREAD

**Issue by Loic57** [PhilippeMarcMeyer/vanillaSelectBox#6]
Hello, 

When you have multiple selects on the same page and click on one to open it and after the second, the first one stayed opened.

Is there any way to have only one select opened at same time ?

**Comment by PhilippeMarcMeyer** [comment]
Interesting remark Loïc
it has never bothered me but you are right the other should close
I should make a list of all instances and close the others when one is opened

As soon as possible

Thanks

Philippe Meyer

**Comment by Hirbod** [comment]
Would love to see this resolved too :). Could you maybe provide a close() method?
I would simply just keep an array of instances and trigger a close on them

**Comment by PhilippeMarcMeyer** [comment]
At last I found some time to implement it !
A click on one selectBox close the other opened boxes.
Thank you for your usefull and kind remarks and advices
