### ISSUE TITLE
create package.json

### ISSUE THREAD

**Issue by turbopixel** [PhilippeMarcMeyer/vanillaSelectBox#67]
Hi there!

Can you create a package.json file like e.g. https://github.com/franciscop/umbrella/blob/master/package.json and share this project at npmjs.com? So I can download this greate tool over `npm install vanillaSelectBox`

**Comment by PhilippeMarcMeyer** [comment]
Package done : hope it's correct
for npm : still to do

**Comment by PhilippeMarcMeyer** [comment]
npm i vanillaselectbox
Thank you turbopixel for helping me pushing this project forward !
:-)
