### ISSUE TITLE
sep = ", "

### ISSUE THREAD

**Issue by chchch** [PhilippeMarcMeyer/vanillaSelectBox#69]
Hi,

It would be nice to change all instances of `sep = ","` to `sep = ", "`, so that selected options are separated by a comma and a space. It looks a little nicer.

Or perhaps include a `userOptions.separator`?

**Comment by PhilippeMarcMeyer** [comment]
I don't close this issue : i'll try to implement it when i have some spare time :)

**Comment by PhilippeMarcMeyer** [comment]
That's a nice to have

**Comment by PhilippeMarcMeyer** [comment]
Done in v1.0.2 : with a new option : itemsSeparator that you may set to ", "
