### ISSUE TITLE
How to Disable the selection of one item at a time or multiple items with a set of items while still displaying these option without them remaing selectable

### ISSUE THREAD

**Issue by applehead1984** [PhilippeMarcMeyer/vanillaSelectBox#7]
Hello is there a way to disable the "selectivity" of an option while still displaying it.
My use case involves historic information via the db that show a client that they can't select an item because they have previously "made use or fulfilled that option" and hence don't need to repeat it.
However the persistent visibility of an item is a clear reminder of their account state.
Is there a specific syntax within the current functionality and it is just a matter of specifying this combination or would this require changes to the code.

Your help would be greatly appreciated.
Thank You!

**Comment by PhilippeMarcMeyer** [comment]
Hello, no there is none. That's a good idea though and i'm going to develop it (as soon as i can...)
Thank you both for the idea and you apreciation !

**Comment by PhilippeMarcMeyer** [comment]
Hello,
The new feature has been added (v 0.35)
You initialize the plugin : 
selectBox = new vanillaSelectBox("#brandsOne", { "maxHeight": 200, "search": true, "placeHolder": "Choose a brand..." });
Then disable
selectBox.disableItems(['Lamborghini','Land Rover']);
or enable items of your choice :
selectBox.enableItems(['Lamborghini','Land Rover']);
