### ISSUE TITLE
self.left and self.top undefined?

### ISSUE THREAD

**Issue by chchch** [PhilippeMarcMeyer/vanillaSelectBox#71]
In lines 558 and 559, 

```javascript
self.drop.style.left = self.left + "px";
self.drop.style.top = self.top + "px";
```

the variables `self.left` and `self.top` don't seem to be defined. Should they have some value?

**Comment by PhilippeMarcMeyer** [comment]
I have just removed those 2 lines absolutly useless : thank you very much for your help :)
