### ISSUE TITLE
Import as a module?

### ISSUE THREAD

**Issue by garak** [PhilippeMarcMeyer/vanillaSelectBox#72]
I'm trying to import this library as a module:

```js
import "vanillaselectbox/vanillaSelectBox";

let mySel = new vanillaSelectBox("#my_id", {search: true});
mySel.enable();
```

but I get `Uncaught ReferenceError: vanillaSelectBox is not defined` error

**Comment by PhilippeMarcMeyer** [comment]
Sorry I don't pratice modular development except a bit of reactjs. I would love but i'm lacking time
