### ISSUE TITLE
"1 items" instead of "1 item"

### ISSUE THREAD

**Issue by apavliukov** [PhilippeMarcMeyer/vanillaSelectBox#73]
Hello,

thank you for your project, it's very helpful for me.

I want to show only items count in the title zone, e.g. "1 item", "2 items" without actual values.

So if I use select like `<select multiple="multiple" size="0">` I see "1 items" instead of "1 item".
![2022-01-31_10-44](https://user-images.githubusercontent.com/4885052/151756025-ac666c73-98a4-4246-9423-fa60409d71f4.png)

Do I need to use some option or it's just a bug?

Thank you.

**Comment by PhilippeMarcMeyer** [comment]
Well I just never thought about it so it's definitely a bug. I put it in my to-do list
Thank you for this good issue ☺️

**Comment by PhilippeMarcMeyer** [comment]
done un v1.0.2 you'll find a demo in the all countries example : 1 country, 2 countries ...

**Comment by apavliukov** [comment]
Works great, thank you!
