### ISSUE TITLE
Inline Button styles

### ISSUE THREAD

**Issue by 2xSamurai** [PhilippeMarcMeyer/vanillaSelectBox#78]
First of all. Hats off to you Sir. This plugin is awesome. Does the job well. 

When using the plugin I faced 2 issues.
1. Inline styling on the button('**.vsb-main button**') and caret icon
2. cant initialize multiple instances of the selectBox using class names.

Solution for 1
I went through the documentation and found a prop that could help "**keepInlineStyles**". But when I added the prop it did nothing. So I inspected the code and found that this prop was not implemented or may be removed. 

I am submitting a pull request with this prop added in along with another prop I added called "**keepInlineCaretStyles**" to remove the inline styles on the **caret**

I feel this could do the minimum job to help style the select box.

```

this.keepInlineStyles = true;
this.keepInlineCaretStyles = true;
```
```

if(options.keepInlineStyles != undefined ) {
          this.keepInlineStyles = options.keepInlineStyles; 
}
if(options.keepInlineCaretStyles != undefined ) {
          this.keepInlineCaretStyles = options.keepInlineCaretStyles;
}

```

This wouldn't break the current setup as it is always set to inline styles **true**. Hope this could help.

Thank you.

**Comment by PhilippeMarcMeyer** [comment]
this is perfect
thank you
