### ISSUE TITLE
with disabled VanillaSelectBox, clicking it submits form

### ISSUE THREAD

**Issue by celtic34fr** [PhilippeMarcMeyer/vanillaSelectBox#88]
When you use VanillaSelectBox in form, if you disable it and click on, form is submitted automatically, even though it shouldn't be.
[example of code to reproduce] (https://jsfiddle.net/citrusMarmelade/f7ovhzkb/)

In your code, if the VanillaSelectBox is disabled, you return directly, you only stop the propagation of the event if the VanillaSelectBox is enabled in order to trigger your own 'click' event. By default, any button is of type 'submit', would it then be possible to change the type of the button associated with the VanillaSelectBox to 'button' by default? this would solve the problem permanently.

**Comment by ale94lko** [comment]
@celtic34fr I have created [#89](https://github.com/PhilippeMarcMeyer/vanillaSelectBox/pull/89) to solve this
