### ISSUE TITLE
css issue for dropdown 

### ISSUE THREAD

**Issue by sudheerk2334** [PhilippeMarcMeyer/vanillaSelectBox#9]
![image](https://user-images.githubusercontent.com/54615663/87120091-44e90f80-c29d-11ea-801a-c4392f9879dd.png)
 my requriment is Dropdown should be same size as input field

**Comment by PhilippeMarcMeyer** [comment]
Sorry for my very late reply : it should be so
can you provide a working example ?

![image](https://user-images.githubusercontent.com/2178299/89873966-7d8d4900-dbbb-11ea-9448-71f092ab7142.png)

**Comment by PhilippeMarcMeyer** [comment]
no news
