### ISSUE TITLE
Unable to stylize the background and border color of input

### ISSUE THREAD

**Issue by tleifj** [PhilippeMarcMeyer/vanillaSelectBox#90]
Is there a reason why the background color and border color are inline styled with !important? It makes it impossible to style using external CSS.

**Comment by PhilippeMarcMeyer** [comment]
Use the option : keepInlineStyles : false
I had issues with css frameworks like bootstrap, so I protected the style of the "button" but due to previous demands I disabled inline styles with the keepInlineStyles property set to false in the user options :)
